/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiuan_it_ipc_utils_H264DecodeUtil */

#ifndef _Included_com_jiuan_it_ipc_utils_H264DecodeUtil
#define _Included_com_jiuan_it_ipc_utils_H264DecodeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiuan_it_ipc_utils_H264DecodeUtil
 * Method:    registeriInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_H264DecodeUtil_registeriInit
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_H264DecodeUtil
 * Method:    decode
 * Signature: ([BI[I[I)[B
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_H264DecodeUtil_decode
  (JNIEnv *, jobject, jbyteArray, jint, jintArray, jintArray, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_H264DecodeUtil
 * Method:    saveJPG
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_H264DecodeUtil_saveJPG
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiuan_it_ipc_utils_H264DecodeUtil
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_H264DecodeUtil_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
