/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myrtspplayer_RtspFromFFMPEG */

#ifndef _Included_com_jiuan_it_ipc_utils_RtspFromFFMPEG
#define _Included_com_jiuan_it_ipc_utils_RtspFromFFMPEG
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_myrtspplayer_RtspFromFFMPEG
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jintArray);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    decode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_decode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    thread_RecvPacket
 * Signature: ()I
 */
 JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_thread_1RecvPacket
   (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    thread_RecvPacket_Mediacodec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_thread_1RecvPacket_1Mediacodec
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    thread_DecodePacket
 * Signature: ([B[D)I
 */
 JNIEXPORT int JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_thread_1DecodePacket
   (JNIEnv *, jobject, jbyteArray, jdoubleArray, jint, jint, jlong, jlongArray, jint);
/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    thread_DecodePacket_audio
 * Signature: ([B[D)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_thread_1DecodePacket_1audio
  (JNIEnv *, jobject, jbyteArray, jdoubleArray);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    thread_MediaCodecPacket
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_thread_1MediaCodecPacket
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_decodeYUV420SP
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_close
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspFromFFMPEG
 * Method:    ConvertTimeBase
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_ConvertTimeBase
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_example_myrtspplayer_RtspFromFFMPEG
 * Method:    PCM2G711a
 * Signature: ([B[BI)[I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_PCM2G711a
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_G711a2PCM
(JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspFromFFMPEG_ClearAudioBuffer
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
