/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myrtspplayer_OpenCV_Test */

#ifndef _Included_com_jiuan_it_ipc_utils_OpenCV
#define _Included_com_jiuan_it_ipc_utils_OpenCV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myrtspplayer_OpenCV_Test
 * Method:    Andon_MosaicIMG
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_OpenCV_Andon_1MosaicIMG
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
