/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myrtspplayer_RtspAudio */

#ifndef _Included_com_jiuan_it_ipc_utils_RtspAudio
#define _Included_com_jiuan_it_ipc_utils_RtspAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    decode
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_decode
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    thread_RecvPacket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_thread_1RecvPacket
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    thread_RecvPacket_Mediacodec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_thread_1RecvPacket_1Mediacodec
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    thread_DecodePacket
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_thread_1DecodePacket
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    thread_MediaCodecPacket
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_thread_1MediaCodecPacket
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_RtspAudio
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_RtspAudio_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
