/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiuan_it_ipc_utils_AudioDecode */

#ifndef _Included_com_jiuan_it_ipc_utils_AudioDecode
#define _Included_com_jiuan_it_ipc_utils_AudioDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_init
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    findAACDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_findAACDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    findG711aDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_findG711aDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    aacDecode
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_aacDecode
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    g711aDecode
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_g711aDecode
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_jiuan_it_ipc_utils_AudioDecode
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jiuan_it_ipc_utils_AudioDecode_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
